-- Phase 7 Migrations: Predictive Intelligence & Autonomous Agents

-- 1. Predictions (Forecasts)
CREATE TABLE IF NOT EXISTS predictions (
    id UUID PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    target_type TEXT NOT NULL, -- 'project', 'goal', 'habit', 'focus', 'anomaly'
    target_id UUID, -- Optional reference to the specific entity
    metric_name TEXT NOT NULL,
    predicted_value NUMERIC NOT NULL,
    confidence_score NUMERIC, -- 0-100
    risk_level TEXT, -- 'low', 'medium', 'high', 'critical'
    insights TEXT, -- Markdown explanation of the forecast
    created_at BIGINT NOT NULL,
    valid_until BIGINT
);

-- 2. Reports (Automated Reviews)
CREATE TABLE IF NOT EXISTS reports (
    id UUID PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    type TEXT NOT NULL, -- 'daily', 'weekly', 'monthly', 'quarterly'
    period_start BIGINT NOT NULL,
    period_end BIGINT NOT NULL,
    content TEXT NOT NULL, -- Markdown content generated by Review Agent
    stats JSONB, -- Stored metrics (e.g., focus hours, tasks completed)
    created_at BIGINT NOT NULL
);

-- 3. Agent Workflows
CREATE TABLE IF NOT EXISTS agent_workflows (
    id UUID PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    agent_type TEXT NOT NULL, -- 'planning', 'research', 'productivity', 'knowledge'
    prompt TEXT NOT NULL,
    status TEXT NOT NULL, -- 'running', 'completed', 'failed'
    output JSONB, -- The structured output steps
    created_at BIGINT NOT NULL,
    completed_at BIGINT
);

-- Add RLS policies for the new tables
ALTER TABLE predictions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own predictions" ON predictions
    FOR ALL USING (auth.uid() = user_id);

ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own reports" ON reports
    FOR ALL USING (auth.uid() = user_id);

ALTER TABLE agent_workflows ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own agent_workflows" ON agent_workflows
    FOR ALL USING (auth.uid() = user_id);
