import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import WorkspaceShell from "@/components/workspace/WorkspaceShell";
import { Sparkles, Calendar, BookOpen, Search, Filter } from "lucide-react";
import { askGemini } from "@/lib/gemini";
import { useExecutionStore } from "@/store/execution-store";
import { useCalendarStore } from "@/store/calendar-store";

export const Route = createFileRoute("/reviews")({
  component: ReviewsPage,
});

type Report = {
  id: string;
  type: 'daily' | 'weekly' | 'monthly';
  dateStr: string;
  content: string;
  isGenerating?: boolean;
};

function ReviewsPage() {
  const { projects, habits } = useExecutionStore();
  const { blocks } = useCalendarStore();
  const [reports, setReports] = useState<Report[]>([
    {
      id: "1",
      type: "weekly",
      dateStr: "Week of June 1st",
      content: "### Weekly Retrospective\\n\\n**Highlights:**\\n- Completed 14 focus hours (up 20% from last week)\\n- Advanced 'Machine Learning' project by 2 milestones\\n\\n**Opportunities:**\\n- You missed 3 days of reading. Schedule this in the morning to build consistency.\\n- Friday afternoon focus drops significantly. Consider lighter tasks."
    }
  ]);
  const [generating, setGenerating] = useState(false);

  const handleGenerateDaily = async () => {
    setGenerating(true);
    
    // Create an optimistic placeholder
    const newId = crypto.randomUUID();
    const newReport: Report = {
      id: newId,
      type: 'daily',
      dateStr: new Date().toLocaleDateString(),
      content: "",
      isGenerating: true
    };
    
    setReports([newReport, ...reports]);
    
    // Build context
    const completedBlocks = blocks.filter(b => b.completed).length;
    const activeProjects = projects.filter(p => p.status === 'active').length;
    
    const contextStr = `Completed Blocks today: ${completedBlocks}\\nActive Projects: ${activeProjects}\\nHabits tracked: ${habits.length}`;
    
    try {
      const response = await askGemini(
        "Generate a brief, punchy daily review report. Highlight what went well, what could be improved, and one key focus for tomorrow. Use markdown formatting.",
        "review",
        contextStr
      );
      
      setReports(prev => prev.map(r => r.id === newId ? { ...r, content: response, isGenerating: false } : r));
    } catch (e) {
      setReports(prev => prev.map(r => r.id === newId ? { ...r, content: "Error generating report.", isGenerating: false } : r));
    } finally {
      setGenerating(false);
    }
  };

  return (
    <WorkspaceShell>
      <div className="mx-auto w-full max-w-5xl p-8 flex flex-col flex-1 text-white selection:bg-purple-500/30">
        <div className="mb-10 flex items-center justify-between">
          <div>
            <h1 className="text-4xl font-black tracking-tight flex items-center gap-3">
              <BookOpen className="h-10 w-10 text-emerald-400" /> Automated Reviews
            </h1>
            <p className="text-zinc-400 mt-2">Zero-effort retrospectives generated by your Review Agent.</p>
          </div>
          
          <button 
            onClick={handleGenerateDaily}
            disabled={generating}
            className="flex items-center gap-2 rounded-xl bg-emerald-500/20 text-emerald-400 px-6 py-3 text-sm font-bold transition hover:bg-emerald-500/30 border border-emerald-500/30 disabled:opacity-50"
          >
            {generating ? <Sparkles className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />} 
            Generate Daily Review
          </button>
        </div>

        <div className="space-y-6">
          {reports.map(report => (
            <div key={report.id} className="rounded-3xl border border-white/10 bg-zinc-950/50 p-8 backdrop-blur-xl group">
              <div className="flex items-center justify-between mb-6 border-b border-white/5 pb-4">
                <div className="flex items-center gap-3">
                  <div className={`p-2 rounded-lg ${
                    report.type === 'daily' ? 'bg-blue-500/20 text-blue-400' :
                    report.type === 'weekly' ? 'bg-purple-500/20 text-purple-400' :
                    'bg-emerald-500/20 text-emerald-400'
                  }`}>
                    <Calendar className="h-5 w-5" />
                  </div>
                  <div>
                    <h3 className="font-bold text-lg capitalize">{report.type} Review</h3>
                    <p className="text-xs text-zinc-500">{report.dateStr}</p>
                  </div>
                </div>
              </div>
              
              <div className="prose prose-invert max-w-none">
                {report.isGenerating ? (
                  <div className="flex items-center gap-3 text-zinc-400">
                    <Sparkles className="h-5 w-5 animate-pulse text-emerald-400" /> Review Agent is analyzing your day...
                  </div>
                ) : (
                  <div dangerouslySetInnerHTML={{ __html: report.content.replace(/\\n/g, '<br/>') }} />
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </WorkspaceShell>
  );
}
