/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as TestAiRouteImport } from './routes/test-ai'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as WorkspaceTasksRouteImport } from './routes/workspace/tasks'
import { Route as WorkspaceSettingsRouteImport } from './routes/workspace/settings'
import { Route as WorkspaceNotesRouteImport } from './routes/workspace/notes'
import { Route as WorkspaceAssistantRouteImport } from './routes/workspace/assistant'
import { Route as WorkspaceAnalyticsRouteImport } from './routes/workspace/analytics'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const TestAiRoute = TestAiRouteImport.update({
  id: '/test-ai',
  path: '/test-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceTasksRoute = WorkspaceTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceNotesRoute = WorkspaceNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAssistantRoute = WorkspaceAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAnalyticsRoute = WorkspaceAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/command-center': typeof CommandCenterRoute
  '/focus': typeof FocusRoute
  '/forecast': typeof ForecastRoute
  '/graph': typeof GraphRoute
  '/habits': typeof HabitsRoute
  '/knowledge': typeof KnowledgeRoute
  '/notes': typeof NotesRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/test-ai': typeof TestAiRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/workspace/assistant': typeof WorkspaceAssistantRoute
  '/workspace/notes': typeof WorkspaceNotesRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/tasks': typeof WorkspaceTasksRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/command-center': typeof CommandCenterRoute
  '/focus': typeof FocusRoute
  '/forecast': typeof ForecastRoute
  '/graph': typeof GraphRoute
  '/habits': typeof HabitsRoute
  '/knowledge': typeof KnowledgeRoute
  '/notes': typeof NotesRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/test-ai': typeof TestAiRoute
  '/workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/workspace/assistant': typeof WorkspaceAssistantRoute
  '/workspace/notes': typeof WorkspaceNotesRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/tasks': typeof WorkspaceTasksRoute
  '/workspace': typeof WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/command-center': typeof CommandCenterRoute
  '/focus': typeof FocusRoute
  '/forecast': typeof ForecastRoute
  '/graph': typeof GraphRoute
  '/habits': typeof HabitsRoute
  '/knowledge': typeof KnowledgeRoute
  '/notes': typeof NotesRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/test-ai': typeof TestAiRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/workspace/assistant': typeof WorkspaceAssistantRoute
  '/workspace/notes': typeof WorkspaceNotesRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/tasks': typeof WorkspaceTasksRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/analytics'
    | '/assistant'
    | '/auth'
    | '/command-center'
    | '/focus'
    | '/forecast'
    | '/graph'
    | '/habits'
    | '/knowledge'
    | '/notes'
    | '/planner'
    | '/profile'
    | '/projects'
    | '/reports'
    | '/reviews'
    | '/settings'
    | '/tasks'
    | '/test-ai'
    | '/workspace'
    | '/workspace/analytics'
    | '/workspace/assistant'
    | '/workspace/notes'
    | '/workspace/settings'
    | '/workspace/tasks'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/analytics'
    | '/assistant'
    | '/auth'
    | '/command-center'
    | '/focus'
    | '/forecast'
    | '/graph'
    | '/habits'
    | '/knowledge'
    | '/notes'
    | '/planner'
    | '/profile'
    | '/projects'
    | '/reports'
    | '/reviews'
    | '/settings'
    | '/tasks'
    | '/test-ai'
    | '/workspace/analytics'
    | '/workspace/assistant'
    | '/workspace/notes'
    | '/workspace/settings'
    | '/workspace/tasks'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/analytics'
    | '/assistant'
    | '/auth'
    | '/command-center'
    | '/focus'
    | '/forecast'
    | '/graph'
    | '/habits'
    | '/knowledge'
    | '/notes'
    | '/planner'
    | '/profile'
    | '/projects'
    | '/reports'
    | '/reviews'
    | '/settings'
    | '/tasks'
    | '/test-ai'
    | '/workspace'
    | '/workspace/analytics'
    | '/workspace/assistant'
    | '/workspace/notes'
    | '/workspace/settings'
    | '/workspace/tasks'
    | '/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  CommandCenterRoute: typeof CommandCenterRoute
  FocusRoute: typeof FocusRoute
  ForecastRoute: typeof ForecastRoute
  GraphRoute: typeof GraphRoute
  HabitsRoute: typeof HabitsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  NotesRoute: typeof NotesRoute
  PlannerRoute: typeof PlannerRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  ReviewsRoute: typeof ReviewsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TestAiRoute: typeof TestAiRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-ai': {
      id: '/test-ai'
      path: '/test-ai'
      fullPath: '/test-ai'
      preLoaderRoute: typeof TestAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/tasks': {
      id: '/workspace/tasks'
      path: '/tasks'
      fullPath: '/workspace/tasks'
      preLoaderRoute: typeof WorkspaceTasksRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/settings': {
      id: '/workspace/settings'
      path: '/settings'
      fullPath: '/workspace/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/notes': {
      id: '/workspace/notes'
      path: '/notes'
      fullPath: '/workspace/notes'
      preLoaderRoute: typeof WorkspaceNotesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/assistant': {
      id: '/workspace/assistant'
      path: '/assistant'
      fullPath: '/workspace/assistant'
      preLoaderRoute: typeof WorkspaceAssistantRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/analytics': {
      id: '/workspace/analytics'
      path: '/analytics'
      fullPath: '/workspace/analytics'
      preLoaderRoute: typeof WorkspaceAnalyticsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceAnalyticsRoute: typeof WorkspaceAnalyticsRoute
  WorkspaceAssistantRoute: typeof WorkspaceAssistantRoute
  WorkspaceNotesRoute: typeof WorkspaceNotesRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceTasksRoute: typeof WorkspaceTasksRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceAnalyticsRoute: WorkspaceAnalyticsRoute,
  WorkspaceAssistantRoute: WorkspaceAssistantRoute,
  WorkspaceNotesRoute: WorkspaceNotesRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceTasksRoute: WorkspaceTasksRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  CommandCenterRoute: CommandCenterRoute,
  FocusRoute: FocusRoute,
  ForecastRoute: ForecastRoute,
  GraphRoute: GraphRoute,
  HabitsRoute: HabitsRoute,
  KnowledgeRoute: KnowledgeRoute,
  NotesRoute: NotesRoute,
  PlannerRoute: PlannerRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  ReviewsRoute: ReviewsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TestAiRoute: TestAiRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
